<?php

/**
 * @file
 *   Integration between Acquia Drupal and Acquia's hosted solr search service.
 */

/**
 * Helper function to cache the Acquia Search version.
 */
function _acquia_search_set_version() {
  // Cache the version in a variable so we can send it at not extra cost.
  $version = \Drupal::config('acquia_search.settings')->get('version');
  $info = system_get_info('module', 'acquia_search');
  // Send the version, or at least the core compatibility as a fallback.
  $new_version = isset($info['version']) ? (string) $info['version'] : (string) $info['core'];
  if ($version != $new_version) {
    \Drupal::configFactory()->getEditable('acquia_connector.settings')->set('version', $new_version)->save();
  }
}

///**
// * Implementation of hook_help().
// */
//function acquia_search_help($path, $arg) {
//  switch ($path) {
//    case 'admin/config/search/apachesolr':
//      $env_id = isset($arg[5]) ? $arg[5] : apachesolr_default_environment();
//      $environment = apachesolr_environment_load($env_id);
//      if (acquia_search_environment_connected($environment) && acquia_agent_subscription_is_active()) {
//        $as_link = l(t('Acquia Search'), 'http://www.acquia.com/products-services/acquia-search');
//        return t("Search is being provided by the !as network service.", array('!as' => $as_link));
//      }
//    break;
//  }
//}
